version: "3"
services:

  account:
    build: ./accounts
    container_name: account
    restart: always
    expose:
      - "4002"
    networks:
      - backend
    env_file:
      - ./accounts/.env

  banking:
    build: ./banking
    container_name: banking
    restart: always
    expose:
      - "4001"
    networks:
      - backend
    env_file:
      - ./banking/.env
    depends_on:
      - redis
    environment:
      - REDIS_CONNECTION_STRING=redis://redis:6379

  nginx-proxy:
    build: ./proxy
    depends_on:
      - banking
      - account
      - redis
    restart: always
    networks:
      - backend
      - gateway
    ports:
      - 80:80

  redis: 
    image: redis:latest
    container_name: redis
    restart: always
    volumes: 
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - backend

volumes:
  redis_volume_data:

    
networks:
  backend:
  gateway:
