# services:
#   - type: web
#     name: retropay-wallet-proxy
#     env: node
#     repo: https://github.com/RetroPay/retropay-wallet-api.git
#     branch: master
#     plan: free
#     rootDir: ./gateway
#     buildFilter: 
#       paths: 
#         - ./gateway/**
#     buildCommand: npm i; npm build
#     startCommand: npm start

#   - type: web
#     name: retro-wallet-proxy-staging
#     env: node
#     repo: https://github.com/RetroPay/retropay-wallet-api.git
#     branch: staging
#     plan: free
#     rootDir: ./gateway
#     buildFilter: 
#       paths: 
#         - ./gateway/**
#     buildCommand: npm i; npm build
#     startCommand: npm start

#   - type: web
#     name: retropay-wallet-accounts-serivce-prod
#     env: node
#     repo: https://github.com/RetroPay/retropay-wallet-api.git
#     branch: master
#     plan: free
#     rootDir: ./accounts
#     buildFilter: 
#       paths: 
#         - ./accounts/**
#     healthCheckPath: /status
#     buildCommand: npm i; npm build
#     startCommand: npm start
#     envVars: 
#       - key: REDIS_CONNECTION_STRING
#         fromService:
#           type: redis
#           name: retropay-wallet-redis
#           property: connectionString
#       - fromGroup: retropay-wallet-account-envs

#   - type: web
#     name: retropay-wallet-accounts-serivce-staging
#     env: node
#     repo: https://github.com/RetroPay/retropay-wallet-api.git
#     branch: staging
#     plan: free
#     rootDir: ./accounts
#     buildFilter: 
#       paths: 
#         - ./accounts/**
#     healthCheckPath: /status
#     buildCommand: npm i; npm build
#     startCommand: npm start
#     envVars: 
#       - key: REDIS_CONNECTION_STRING
#         fromService:
#           type: redis
#           name: retropay-wallet-redis
#           property: connectionString
#       - fromGroup: retropay-wallet-account-envs-staging

#   - type: web
#     name: retropay-wallet-banking-serivce-staging
#     env: node
#     repo: https://github.com/RetroPay/retropay-wallet-api.git
#     branch: staging
#     plan: free
#     rootDir: ./banking
#     buildFilter: 
#       paths: 
#         - ./banking/**
#     healthCheckPath: /status
#     buildCommand: npm i; npm build
#     startCommand: npm start
#     envVars: 
#       - key: REDIS_CONNECTION_STRING
#         fromService:
#           type: redis
#           name: retropay-wallet-redis
#           property: connectionString
#       - fromGroup: retropay-wallet-banking-envs-staging

#   - type: web
#     name: retropay-wallet-banking-serivce-prod
#     env: node
#     repo: https://github.com/RetroPay/retropay-wallet-api.git
#     branch: master
#     plan: free
#     rootDir: ./banking
#     buildFilter: 
#       paths: 
#         - ./banking/**
#     healthCheckPath: /status
#     buildCommand: npm i; npm build
#     startCommand: npm start
#     envVars: 
#       - key: REDIS_CONNECTION_STRING
#         fromService:
#           type: redis
#           name: retropay-wallet-redis
#           property: connectionString
#       - fromGroup: retropay-wallet-banking-envs

#   - type: redis
#     name: retropay-wallet-redis
#     plan: free
#     ipAllowList: []

services:
  - type: web
    name: proxy
    env: node
    repo: https://github.com/RetroPay/retropay-wallet-api.git
    branch: master
    plan: free
    rootDir: ./gateway
    buildFilter: 
      paths: 
        - ./gateway/**
    buildCommand: npm i; npm build
    startCommand: npm start

  - type: web
    name: proxy-staging
    env: node
    repo: https://github.com/RetroPay/retropay-wallet-api.git
    branch: staging
    plan: free
    rootDir: ./gateway
    buildFilter: 
      paths: 
        - ./gateway/**
    buildCommand: npm i; npm build
    startCommand: npm start

  - type: web
    name: retropay-accounts-prod
    env: node
    repo: https://github.com/RetroPay/retropay-wallet-api.git
    branch: master
    plan: free
    rootDir: ./accounts
    buildFilter: 
      paths: 
        - ./accounts/**
    healthCheckPath: /status
    buildCommand: npm i; npm build
    startCommand: npm start
    envVars: 
      - key: REDIS_CONNECTION_STRING
        fromService:
          type: redis
          name: retropay-redis
          property: connectionString
      - fromGroup: retropay-account-envs

  - type: web
    name: retropay-accounts-staging
    env: node
    repo: https://github.com/RetroPay/retropay-wallet-api.git
    branch: staging
    plan: free
    rootDir: ./accounts
    buildFilter: 
      paths: 
        - ./accounts/**
    healthCheckPath: /status
    buildCommand: npm i; npm build
    startCommand: npm start
    envVars: 
      - key: REDIS_CONNECTION_STRING
        fromService:
          type: redis
          name: retropay-redis
          property: connectionString
      - fromGroup: retropay-account-envs-staging

  - type: web
    name: retropay-banking-staging
    env: node
    repo: https://github.com/RetroPay/retropay-wallet-api.git
    branch: staging
    plan: free
    rootDir: ./banking
    buildFilter: 
      paths: 
        - ./banking/**
    healthCheckPath: /status
    buildCommand: npm i; npm build
    startCommand: npm start
    envVars: 
      - key: REDIS_CONNECTION_STRING
        fromService:
          type: redis
          name: retropay-redis
          property: connectionString
      - fromGroup: retropay-banking-envs-staging

  - type: web
    name: retropay-banking-prod
    env: node
    repo: https://github.com/RetroPay/retropay-wallet-api.git
    branch: master
    plan: free
    rootDir: ./banking
    buildFilter: 
      paths: 
        - ./banking/**
    healthCheckPath: /status
    buildCommand: npm i; npm build
    startCommand: npm start
    envVars: 
      - key: REDIS_CONNECTION_STRING
        fromService:
          type: redis
          name: retropay-redis
          property: connectionString
      - fromGroup: retropay-banking-envs

  - type: redis
    name: retropay-redis
    plan: free
    ipAllowList: []