

name: CI

on:
  pull_request:
    branches: [ "master", "staging" ]

jobs:
  ci_verification:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Test accounts service
      working-directory: ./accounts
      run: 
        npm ci
        npm test
    - name: Test banking service
      working-directory: ./banking
      run: 
        npm ci
        npm test
